package com.exproject.backend.location_category.info;

public enum ELocationCategory {
    SNACK,
    RESTAURANT,
    CAFE,
    NIGHT_MARKET,
    MARKET,
    SPECIALITY,
    HOTEL,
    AMUSEMENT_WATER_PARK,
    ZOO,
    AQUARIUM,
    NIGHTLIFE,
    FESTIVAL,
    CULTURE_PERFORMANCE,
    MOUNTAIN,
    CAVE,
    CAMPING,
    DIVING,
    MUSEUM,
    CITADEL_PALACE,
    CHURCH_TEMPLE_PAGODA,
    OLD_BATTLEFIELD,
    BEACH,
    ISLAND,
    YATCH_CRUISE,
    VIEWPOINT,
    RESORT,
    HOMESTAY,
    SPA,
    RIVER,
    FLOWER_FIELD_GARDEN,
    BAR,
    WALKING_STREET,
    WATERFALL,
}
