services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quanbro7
      POSTGRES_DB: loko_project
      PG_DATA: /data/postgres

    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - backend
    restart: unless-stopped


  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: loko-project-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loko_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: quanbro7
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db: