spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loko_project
    username: postgres
    password: quanbro7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
