ATTRACTIONS_FILE = 'attractions_with_tags.json'
TIME_MATRIX_FILE = 'time_matrix.txt'
DAY_START_TIME = 8 * 60
DAY_END_TIME = 22 * 60
MAX_DAY_DURATION = DAY_END_TIME - DAY_START_TIME
LUNCH_START_MINS = (11 * 60 + 30) - DAY_START_TIME
LUNCH_END_MINS = (13 * 60 + 30) - DAY_START_TIME
LUNCH_PENALTY = 500